const ActionTypes = {
    SET_PRODUCTS: 'SET_PRODUCTS',
    SELECTED_PRODUCT: 'SELECTED_PRODUCT',
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    ADJUST_ITEM_QTY: 'ADJUST_ITEM_QTY',
    EMPTY_CART: 'EMPTY_CART'
}

export default ActionTypes